name: Flow-CI-Honkit

on:
  push:
    branches:
        - master
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and deploy
        env:
          USER_EMAIL: ${{secrets.USER_EMAIL}}
          USER_NAME: ${{secrets.USER_NAME}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          chmod +x ./entrypoint.sh
          ./entrypoint.sh
